# Generated by Django 5.2.7 on 2026-04-18 17:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenders", "0002_tender_spec_language_tender_spec_text"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agency_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("legal_name", models.CharField(max_length=500)),
                ("gstin", models.CharField(max_length=15, unique=True)),
                ("ministry", models.CharField(max_length=500)),
                ("contact_name", models.CharField(max_length=255)),
                ("contact_email", models.EmailField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="PENDING_APPROVAL",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "agencies_agency",
            },
        ),
        migrations.CreateModel(
            name="EmailVerificationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verification_token",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "agencies_emailverificationtoken",
            },
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("email", models.EmailField(max_length=254)),
                ("role", models.CharField(max_length=20)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="agencies.agency",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "agencies_invitation",
            },
        ),
        migrations.CreateModel(
            name="TenderSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tender_ref", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=500)),
                ("category", models.CharField(max_length=255)),
                (
                    "estimated_value",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("submission_deadline", models.DateTimeField()),
                ("publication_date", models.DateTimeField(blank=True, null=True)),
                ("buyer_name", models.CharField(max_length=500)),
                ("spec_text", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("FLAGGED", "Flagged"),
                            ("CLEARED", "Cleared"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("review_note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="agencies.agency",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tender",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission",
                        to="tenders.tender",
                    ),
                ),
            ],
            options={
                "db_table": "agencies_tendersubmission",
                "indexes": [
                    models.Index(
                        fields=["agency", "status"],
                        name="agencies_te_agency__caf016_idx",
                    ),
                    models.Index(
                        fields=["agency", "created_at"],
                        name="agencies_te_agency__5c8274_idx",
                    ),
                ],
            },
        ),
    ]
