# Generated by Django 5.2.7 on 2026-04-12 17:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bids", "0001_initial"),
        ("tenders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollusionRing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ring_id", models.CharField(max_length=255, unique=True)),
                ("member_bidder_ids", models.JSONField(default=list)),
                ("member_count", models.PositiveIntegerField(default=0)),
                (
                    "detected_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "graph_collusionring",
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="graph_collu_is_acti_96d46c_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GraphNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metadata", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bidder",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_node",
                        to="bids.bidder",
                    ),
                ),
            ],
            options={
                "db_table": "graph_graphnode",
            },
        ),
        migrations.CreateModel(
            name="GraphEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "edge_type",
                    models.CharField(
                        choices=[
                            ("CO_BID", "Co-Bid"),
                            ("SHARED_DIRECTOR", "Shared Director"),
                            ("SHARED_ADDRESS", "Shared Address"),
                        ],
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "tender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graph_edges",
                        to="tenders.tender",
                    ),
                ),
                (
                    "source_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_edges",
                        to="graph.graphnode",
                    ),
                ),
                (
                    "target_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_edges",
                        to="graph.graphnode",
                    ),
                ),
            ],
            options={
                "db_table": "graph_graphedge",
                "indexes": [
                    models.Index(
                        fields=["edge_type"], name="graph_graph_edge_ty_e6fc4d_idx"
                    ),
                    models.Index(
                        fields=["source_node", "target_node", "edge_type"],
                        name="graph_graph_source__2ab606_idx",
                    ),
                ],
            },
        ),
    ]
