# Generated by Django 5.2.7 on 2026-04-12 17:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("threshold", models.PositiveSmallIntegerField(default=70)),
                ("category", models.CharField(blank=True, default="", max_length=255)),
                ("email_enabled", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "alerts_alertsettings",
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("HIGH_RISK_SCORE", "High Risk Score"),
                            ("COLLUSION_RING", "Collusion Ring Detected"),
                            ("RED_FLAG", "Red Flag Raised"),
                        ],
                        default="HIGH_RISK_SCORE",
                        max_length=30,
                    ),
                ),
                ("fraud_risk_score", models.PositiveSmallIntegerField()),
                ("top_red_flags", models.JSONField(default=list)),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                            ("RETRYING", "Retrying"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="tenders.tender",
                    ),
                ),
            ],
            options={
                "db_table": "alerts_alert",
                "ordering": ["-created_at"],
            },
        ),
    ]
