# Generated by Django 4.2.16 on 2026-04-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alert_is_read_title_detail_link_permanently_failed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('HIGH_RISK_SCORE', 'High Risk Score'), ('COLLUSION_RING', 'Collusion Ring Detected'), ('RED_FLAG', 'Red Flag Raised'), ('SCORING_FAILURE', 'Scoring Failure'), ('TENDER_FLAGGED', 'Tender Flagged')], default='HIGH_RISK_SCORE', max_length=30),
        ),
    ]
