# Generated by Django 5.2.7 on 2026-04-12 17:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tender_id", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=500)),
                ("category", models.CharField(max_length=255)),
                (
                    "estimated_value",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("currency", models.CharField(default="INR", max_length=10)),
                ("submission_deadline", models.DateTimeField()),
                ("buyer_id", models.CharField(max_length=255)),
                ("buyer_name", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("CLOSED", "Closed"),
                            ("AWARDED", "Awarded"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("publication_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tenders_tender",
                "indexes": [
                    models.Index(
                        fields=["category"], name="tenders_ten_categor_51be61_idx"
                    ),
                    models.Index(
                        fields=["buyer_name"], name="tenders_ten_buyer_n_cf8f44_idx"
                    ),
                    models.Index(
                        fields=["submission_deadline"],
                        name="tenders_ten_submiss_e19e8b_idx",
                    ),
                    models.Index(
                        fields=["status"], name="tenders_ten_status_955cba_idx"
                    ),
                ],
            },
        ),
    ]
