# Generated by Django 5.2.7 on 2026-04-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="spec_language",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="tender",
            name="spec_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
