# Generated by Django 5.2.7 on 2026-04-12 17:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bids", "0001_initial"),
        ("tenders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RuleDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rule_code", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("parameters", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "detection_ruledefinition",
            },
        ),
        migrations.CreateModel(
            name="RedFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flag_type",
                    models.CharField(
                        choices=[
                            ("SINGLE_BIDDER", "Single Bidder"),
                            ("PRICE_ANOMALY", "Price Anomaly"),
                            ("REPEAT_WINNER", "Repeat Winner"),
                            ("SHORT_DEADLINE", "Short Deadline"),
                            ("LINKED_ENTITIES", "Linked Entities"),
                            ("COVER_BID_PATTERN", "Cover Bid Pattern"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                ("rule_version", models.CharField(default="1.0", max_length=50)),
                ("trigger_data", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("raised_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("cleared_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bidder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="red_flags",
                        to="bids.bidder",
                    ),
                ),
                (
                    "tender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="red_flags",
                        to="tenders.tender",
                    ),
                ),
            ],
            options={
                "db_table": "detection_redflag",
                "indexes": [
                    models.Index(
                        fields=["tender", "is_active"],
                        name="detection_r_tender__e826f1_idx",
                    ),
                    models.Index(
                        fields=["flag_type"], name="detection_r_flag_ty_fbbaf3_idx"
                    ),
                    models.Index(
                        fields=["severity"], name="detection_r_severit_8446d0_idx"
                    ),
                ],
            },
        ),
    ]
