# Generated by Django 5.2.7 on 2026-04-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redflag",
            name="flag_type",
            field=models.CharField(
                choices=[
                    ("SINGLE_BIDDER", "Single Bidder"),
                    ("PRICE_ANOMALY", "Price Anomaly"),
                    ("REPEAT_WINNER", "Repeat Winner"),
                    ("SHORT_DEADLINE", "Short Deadline"),
                    ("LINKED_ENTITIES", "Linked Entities"),
                    ("COVER_BID_PATTERN", "Cover Bid Pattern"),
                    ("SPEC_TAILORING", "Specification Tailoring"),
                    ("SPEC_COPY_PASTE", "Copy-Paste Fraud"),
                    ("SPEC_VAGUE_SCOPE", "Vague Scope"),
                    ("SPEC_UNUSUAL_RESTRICTION", "Unusual Restriction"),
                ],
                max_length=50,
            ),
        ),
    ]
