# Generated by Django 5.2.7 on 2026-04-12 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bids", "0001_initial"),
        ("graph", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_bids", models.PositiveIntegerField(default=0)),
                ("total_wins", models.PositiveIntegerField(default=0)),
                (
                    "win_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "avg_bid_deviation",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("active_red_flag_count", models.PositiveIntegerField(default=0)),
                (
                    "highest_fraud_risk_score",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "risk_status",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Risk"),
                            ("MEDIUM", "Medium Risk"),
                            ("HIGH_RISK", "High Risk"),
                        ],
                        default="LOW",
                        max_length=10,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bidder",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_profile",
                        to="bids.bidder",
                    ),
                ),
                (
                    "collusion_ring",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="company_profiles",
                        to="graph.collusionring",
                    ),
                ),
            ],
            options={
                "db_table": "companies_companyprofile",
                "indexes": [
                    models.Index(
                        fields=["risk_status"], name="companies_c_risk_st_9db02f_idx"
                    )
                ],
            },
        ),
    ]
