# Generated by Django 5.2.7 on 2026-04-12 17:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FraudRiskScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveSmallIntegerField()),
                (
                    "ml_anomaly_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "ml_collusion_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("red_flag_contribution", models.PositiveSmallIntegerField(default=0)),
                (
                    "model_version",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("weight_config", models.JSONField(default=dict)),
                (
                    "computed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "tender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fraud_risk_scores",
                        to="tenders.tender",
                    ),
                ),
            ],
            options={
                "db_table": "scoring_fraudriskscore",
                "ordering": ["-computed_at"],
                "indexes": [
                    models.Index(
                        fields=["tender", "computed_at"],
                        name="scoring_fra_tender__0a95a1_idx",
                    )
                ],
            },
        ),
    ]
