# Generated by Django 5.2.7 on 2026-04-12 17:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MLModelVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("ISOLATION_FOREST", "Isolation Forest"),
                            ("RANDOM_FOREST", "Random Forest"),
                        ],
                        max_length=50,
                    ),
                ),
                ("version", models.CharField(max_length=100)),
                ("trained_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("feature_importances", models.JSONField(default=dict)),
                ("model_artifact_path", models.CharField(max_length=500)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "xai_mlmodelversion",
                "indexes": [
                    models.Index(
                        fields=["model_type", "is_active"],
                        name="xai_mlmodel_model_t_f6514c_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SHAPExplanation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_version", models.CharField(max_length=100)),
                ("rule_engine_version", models.CharField(max_length=100)),
                ("shap_values", models.JSONField(default=dict)),
                ("top_factors", models.JSONField(default=list)),
                ("shap_failed", models.BooleanField(default=False)),
                (
                    "computed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "tender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shap_explanations",
                        to="tenders.tender",
                    ),
                ),
            ],
            options={
                "db_table": "xai_shapexplanation",
                "ordering": ["-computed_at"],
                "indexes": [
                    models.Index(
                        fields=["tender", "computed_at"],
                        name="xai_shapexp_tender__cc5c9c_idx",
                    )
                ],
            },
        ),
    ]
