# Generated by Django 5.2.7 on 2026-04-14 16:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("detection", "0002_alter_redflag_flag_type"),
        ("tenders", "0002_tender_spec_language_tender_spec_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecAnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        default="paraphrase-multilingual-MiniLM-L12-v2", max_length=200
                    ),
                ),
                ("embedding_dim", models.PositiveSmallIntegerField(default=384)),
                (
                    "spec_language",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("tailoring_similarity", models.FloatField(blank=True, null=True)),
                (
                    "tailoring_matched_tender_id",
                    models.IntegerField(blank=True, null=True),
                ),
                ("copy_paste_similarity", models.FloatField(blank=True, null=True)),
                (
                    "copy_paste_matched_tender_id",
                    models.IntegerField(blank=True, null=True),
                ),
                ("vagueness_score", models.FloatField(blank=True, null=True)),
                ("unusual_restriction_score", models.FloatField(blank=True, null=True)),
                ("flags_raised", models.JSONField(default=list)),
                (
                    "analyzed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "analysis_duration_ms",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("error", models.TextField(blank=True, default="")),
                (
                    "tender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spec_analyses",
                        to="tenders.tender",
                    ),
                ),
            ],
            options={
                "db_table": "nlp_specanalysisresult",
                "indexes": [
                    models.Index(
                        fields=["tender", "analyzed_at"],
                        name="nlp_specana_tender__35688a_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SpecClauseHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sentence_text", models.TextField()),
                ("sentence_index", models.PositiveSmallIntegerField()),
                ("relevance_score", models.FloatField()),
                ("reason", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "red_flag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clause_highlights",
                        to="detection.redflag",
                    ),
                ),
                (
                    "tender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clause_highlights",
                        to="tenders.tender",
                    ),
                ),
            ],
            options={
                "db_table": "nlp_specclausehighlight",
                "ordering": ["-relevance_score"],
                "indexes": [
                    models.Index(
                        fields=["tender", "red_flag"],
                        name="nlp_speccla_tender__e892bd_idx",
                    )
                ],
            },
        ),
    ]
