# Generated by Django 5.2.7 on 2026-04-12 17:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bidder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bidder_id", models.CharField(max_length=255, unique=True)),
                ("bidder_name", models.CharField(max_length=500)),
                ("registered_address", models.TextField(blank=True, default="")),
                ("director_names", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "bids_bidder",
                "indexes": [
                    models.Index(
                        fields=["bidder_name"], name="bids_bidder_bidder__91e28f_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Bid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bid_id", models.CharField(max_length=255, unique=True)),
                ("bid_amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("submission_timestamp", models.DateTimeField()),
                ("is_winner", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "tender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to="tenders.tender",
                    ),
                ),
                (
                    "bidder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to="bids.bidder",
                    ),
                ),
            ],
            options={
                "db_table": "bids_bid",
                "indexes": [
                    models.Index(fields=["tender"], name="bids_bid_tender__36d491_idx"),
                    models.Index(fields=["bidder"], name="bids_bid_bidder__bb90ba_idx"),
                    models.Index(
                        fields=["submission_timestamp"],
                        name="bids_bid_submiss_3de838_idx",
                    ),
                ],
            },
        ),
    ]
