# Generated by Django 5.2.7 on 2026-04-12 17:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("USER_LOGIN", "User Login"),
                            ("USER_LOGOUT", "User Logout"),
                            ("USER_LOGIN_FAILED", "User Login Failed"),
                            ("USER_LOCKED", "User Account Locked"),
                            ("TENDER_INGESTED", "Tender Ingested"),
                            ("BID_INGESTED", "Bid Ingested"),
                            ("SCORE_COMPUTED", "Score Computed"),
                            ("RED_FLAG_RAISED", "Red Flag Raised"),
                            ("RED_FLAG_CLEARED", "Red Flag Cleared"),
                            ("ALERT_SENT", "Alert Sent"),
                            ("ALERT_FAILED", "Alert Delivery Failed"),
                            ("STATUS_CHANGED", "Status Changed"),
                            ("MODEL_RETRAINED", "ML Model Retrained"),
                            ("SHAP_FAILED", "SHAP Computation Failed"),
                            ("JWT_INVALID_KEY", "JWT Invalid Signing Key"),
                            ("EXPORT_GENERATED", "Audit Export Generated"),
                            ("RULE_ADDED", "Rule Definition Added"),
                        ],
                        max_length=30,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "affected_entity_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "affected_entity_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("data_snapshot", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "db_table": "audit_auditlog",
                "ordering": ["-timestamp"],
            },
        ),
    ]
