# Generated by Django 4.2.16 on 2026-04-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(choices=[('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('USER_LOGIN_FAILED', 'User Login Failed'), ('USER_LOCKED', 'User Account Locked'), ('TENDER_INGESTED', 'Tender Ingested'), ('BID_INGESTED', 'Bid Ingested'), ('SCORE_COMPUTED', 'Score Computed'), ('RED_FLAG_RAISED', 'Red Flag Raised'), ('RED_FLAG_CLEARED', 'Red Flag Cleared'), ('ALERT_SENT', 'Alert Sent'), ('ALERT_FAILED', 'Alert Delivery Failed'), ('STATUS_CHANGED', 'Status Changed'), ('MODEL_RETRAINED', 'ML Model Retrained'), ('SHAP_FAILED', 'SHAP Computation Failed'), ('JWT_INVALID_KEY', 'JWT Invalid Signing Key'), ('EXPORT_GENERATED', 'Audit Export Generated'), ('RULE_ADDED', 'Rule Definition Added'), ('EXPLANATION_GENERATED', 'Explanation Generated'), ('SPEC_UPDATED', 'Tender Spec Text Updated'), ('AGENCY_REGISTERED', 'Agency Registered'), ('AGENCY_STATUS_CHANGED', 'Agency Status Changed'), ('INVITATION_CREATED', 'Invitation Created'), ('INVITATION_ACCEPTED', 'Invitation Accepted'), ('MEMBER_DEACTIVATED', 'Member Deactivated'), ('PERMISSION_DENIED', 'Permission Denied'), ('TENDER_SUBMITTED', 'Tender Submitted'), ('TENDER_CLEARED', 'Tender Cleared'), ('GOV_AUDITOR_ACCESS', 'Government Auditor Access')], max_length=30),
        ),
    ]
